name: JMeter Performance Test

on:
  push:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter test
        run: |
          mkdir -p results
          apache-jmeter-5.6.3/bin/jmeter \
            -n \
            -t Bookstore.jmx \
            -l results/result.jtl

      - name: Generate HTML Dashboard
        if: always()
        run: |
          apache-jmeter-5.6.3/bin/jmeter \
            -g results/result.jtl \
            -o results/html-report

      - name: Upload JMeter report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: results/html-report

      - name: Upload JTL results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/result.jtl